server:
  port: 8056

spring:
  application:
    name: hystrix

eureka:
  client:
    register-with-eureka: false
    #    fetch-registry: false
    serviceUrl:
      defaultZone: http://lz:123456@localhost:8761/eureka

#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true